name: academix
description: !include academix_description.yaml

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.2
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  go_router: ^9.0.0
  url_strategy: ^0.2.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0
  cloud_firestore: ^4.8.2
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.2.0
  fluentui_system_icons: ^1.1.205
  firebase_storage: ^11.2.4
  file_picker: ^5.3.2
  flutter_carousel_widget: ^2.0.4
  cached_network_image: ^3.2.3
  timeago: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # fonts
    - assets/fonts/sacramento/
    - assets/fonts/gilroy/
    # logo
    - assets/logo/light/
    - assets/logo/dark/
    - assets/logo/mirage/

  fonts:
    # Gilroy Font
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf

    # Sacramento Font
    - family: Sacramento
      fonts:
        - asset: assets/fonts/sacramento/Sacramento-Regular.ttf
