name: academix
description: !include academix_description.yaml

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.1.2
  flutter_riverpod: ^2.3.6
  flutter_svg: ^2.0.7
  go_router: ^9.0.0
  url_strategy: ^0.2.0
  firebase_auth: ^4.6.3
  firebase_core: ^2.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    # fonts
    - assets/fonts/sacramento/
    - assets/fonts/ysabeau_office/
    # logo
    - assets/logo/light/
    - assets/logo/dark/
    - assets/logo/mirage/

  fonts:
    # Sacramento Font
    - family: Sacramento
      fonts:
        - asset: assets/fonts/sacramento/Sacramento-Regular.ttf
    # Ysabeau Office Font
    - family: Ysabeau
      fonts:
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-Light.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-LightItalic.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-Regular.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-Black.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-BlackItalic.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-Bold.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-BoldItalic.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-ExtraBold.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-ExtraBoldItalic.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-ExtraLight.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-ExtraLightItalic.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-Italic.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-Medium.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-MediumItalic.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-SemiBold.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-SemiBoldItalic.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-Thin.ttf
        - asset: assets/fonts/ysabeau_office/YsabeauOffice-ThinItalic.ttf
    # Gilroy Font
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
        - asset: assets/fonts/gilroy/Gilroy-LightItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-RegularItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Black.ttf
        - asset: assets/fonts/gilroy/Gilroy-BlackItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
        - asset: assets/fonts/gilroy/Gilroy-BoldItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
        - asset: assets/fonts/gilroy/Gilroy-ExtraBoldItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
        - asset: assets/fonts/gilroy/Gilroy-HeavyItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
        - asset: assets/fonts/gilroy/Gilroy-MediumItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
        - asset: assets/fonts/gilroy/Gilroy-SemiBoldItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-Thin.ttf
        - asset: assets/fonts/gilroy/Gilroy-ThinItalic.ttf
        - asset: assets/fonts/gilroy/Gilroy-UltraLight.ttf
        - asset: assets/fonts/gilroy/Gilroy-UltraLightItalic.ttf
